In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### import data

In [2]:
df = pd.read_csv(r"C:\Users\Anish Kumar\Downloads\large_sales.csv")

In [4]:
df.head(5)

,Order_ID,Order_Date,City,Product,Category,Channel,Customer_Segment,Payment_Method,Quantity,Unit_Price,...,Sales,Cost,Profit,Profit_Margin_Pct,Month,Month_Name,Quarter,Year,Day_Name,Weekend
0,ORD0097384,2024-01-01,Bengaluru,Tablet,Office,Store,Consumer,Debit Card,1,43384.87,...,35041.96,23400.29,11641.67,33.22,1,January,Q1,2024,Monday,No
1,ORD0054822,2024-01-01,Bengaluru,Headphones,Accessories,Marketplace,Home Office,Debit Card,7,35564.72,...,247832.75,181138.97,66693.78,26.91,1,January,Q1,2024,Monday,No
2,ORD0006567,2024-01-01,Hyderabad,Headphones,Office,Marketplace,Corporate,UPI,6,98829.18,...,529941.83,315728.84,214212.99,40.42,1,January,Q1,2024,Monday,No
3,ORD0037082,2024-01-01,Bengaluru,Monitor,Accessories,Marketplace,Consumer,UPI,4,12506.66,...,46940.00,30202.41,16737.59,35.66,1,January,Q1,2024,Monday,No
4,ORD0076597,2024-01-01,Kolkata,Mouse,Electronics,Online,Corporate,Debit Card,3,73625.86,...,168087.84,129593.53,38494.31,22.90,1,January,Q1,2024,Monday,No

In [5]:
df.tail(5)

,Order_ID,Order_Date,City,Product,Category,Channel,Customer_Segment,Payment_Method,Quantity,Unit_Price,...,Sales,Cost,Profit,Profit_Margin_Pct,Month,Month_Name,Quarter,Year,Day_Name,Weekend
99995,ORD0084825,2025-12-31,Delhi,Keyboard,Accessories,Store,Corporate,UPI,1,116767.52,...,90553.21,64568.50,25984.71,28.70,12,December,Q4,2025,Wednesday,No
99996,ORD0031111,2025-12-31,Pune,Tablet,Office,Marketplace,Consumer,Debit Card,3,112068.10,...,314519.12,238568.44,75950.68,24.15,12,December,Q4,2025,Wednesday,No
99997,ORD0067132,2025-12-31,Hyderabad,Headphones,Electronics,Store,Home Office,Credit Card,5,14379.50,...,63161.95,49297.27,13864.68,21.95,12,December,Q4,2025,Wednesday,No
99998,ORD0056816,2025-12-31,Kolkata,Printer,Accessories,Online,Home Office,Net Banking,2,54367.81,...,84879.02,53897.89,30981.13,36.50,12,December,Q4,2025,Wednesday,No
99999,ORD0023522,2025-12-31,Mumbai,Laptop,Office,Store,Consumer,Credit Card,3,3355.02,...,9774.18,8544.38,1229.80,12.58,12,December,Q4,2025,Wednesday,No

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Order_ID           100000 non-null  str
 1   Order_Date         100000 non-null  str
 2   City               100000 non-null  str
 3   Product            100000 non-null  str
 4   Category           100000 non-null  str
 5   Channel            100000 non-null  str
 6   Customer_Segment   100000 non-null  str
 7   Payment_Method     99700 non-null   str
 8   Quantity           100000 non-null  int64
 9   Unit_Price         100000 non-null  float64
 10  Discount_Pct       99500 non-null   float64
 11  Customer_Age       100000 non-null  int64
 12  Customer_Rating    99000 non-null   float64
 13  Gross_Sales        100000 non-null  float64
 14  Discount_Amount    100000 non-null  float64
 15  Sales              100000 non-null  float64
 16  Cost               100000 non-null  float64
 17  Profit             100000 non-null  float64
 18  Profit_Margin_Pct  100000 non-null  float64
 19  Month              100000 non-null  int64
 20  Month_Name         100000 non-null  str
 21  Quarter            100000 non-null  str
 22  Year               100000 non-null  int64
 23  Day_Name           100000 non-null  str
 24  Weekend            100000 non-null  str
dtypes: float64(9), int64(4), str(12)
memory usage: 19.1 MB

In [7]:
df.columns

Index(['Order_ID', 'Order_Date', 'City', 'Product', 'Category', 'Channel',
       'Customer_Segment', 'Payment_Method', 'Quantity', 'Unit_Price',
       'Discount_Pct', 'Customer_Age', 'Customer_Rating', 'Gross_Sales',
       'Discount_Amount', 'Sales', 'Cost', 'Profit', 'Profit_Margin_Pct',
       'Month', 'Month_Name', 'Quarter', 'Year', 'Day_Name', 'Weekend'],
      dtype='str')

In [8]:
df.isnull().sum()

Order_ID                0
Order_Date              0
City                    0
Product                 0
Category                0
Channel                 0
Customer_Segment        0
Payment_Method        300
Quantity                0
Unit_Price              0
Discount_Pct          500
Customer_Age            0
Customer_Rating      1000
Gross_Sales             0
Discount_Amount         0
Sales                   0
Cost                    0
Profit                  0
Profit_Margin_Pct       0
Month                   0
Month_Name              0
Quarter                 0
Year                    0
Day_Name                0
Weekend                 0
dtype: int64

### Fill The Payment_Method Value

In [9]:
df["Payment_Method"].unique()

<StringArray>
['Debit Card', 'UPI', 'Cash', 'Credit Card', 'Net Banking', nan]
Length: 6, dtype: str

In [13]:
df["Payment_Method"] = df["Payment_Method"].fillna(
    df["Payment_Method"].mode()[0]
)

### ### Fill The Discount_Pct Value

In [11]:
df["Discount_Pct"]

0        19.23
1         0.45
2        10.63
3         6.17
4        23.90
         ...
99995    22.45
99996     6.45
99997    12.15
99998    21.94
99999     2.89
Name: Discount_Pct, Length: 100000, dtype: float64

In [14]:
df["Discount_Pct"] = df["Discount_Pct"].fillna(
    df["Discount_Pct"].median()
)

### Fill The Customer_Rating Value

In [12]:
df["Customer_Rating"]

0        1.6
1        2.6
2        1.3
3        1.9
4        2.1
        ...
99995    2.1
99996    4.4
99997    3.4
99998    4.1
99999    2.7
Name: Customer_Rating, Length: 100000, dtype: float64

In [15]:
df["Customer_Rating"] = df["Customer_Rating"].fillna(
    df["Customer_Rating"].median()
)

In [18]:
df.isna().sum()

Order_ID             0
Order_Date           0
City                 0
Product              0
Category             0
Channel              0
Customer_Segment     0
Payment_Method       0
Quantity             0
Unit_Price           0
Discount_Pct         0
Customer_Age         0
Customer_Rating      0
Gross_Sales          0
Discount_Amount      0
Sales                0
Cost                 0
Profit               0
Profit_Margin_Pct    0
Month                0
Month_Name           0
Quarter              0
Year                 0
Day_Name             0
Weekend              0
dtype: int64

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Order_ID           100000 non-null  str
 1   Order_Date         100000 non-null  str
 2   City               100000 non-null  str
 3   Product            100000 non-null  str
 4   Category           100000 non-null  str
 5   Channel            100000 non-null  str
 6   Customer_Segment   100000 non-null  str
 7   Payment_Method     100000 non-null  str
 8   Quantity           100000 non-null  int64
 9   Unit_Price         100000 non-null  float64
 10  Discount_Pct       100000 non-null  float64
 11  Customer_Age       100000 non-null  int64
 12  Customer_Rating    100000 non-null  float64
 13  Gross_Sales        100000 non-null  float64
 14  Discount_Amount    100000 non-null  float64
 15  Sales              100000 non-null  float64
 16  Cost               100000 non-null  float64
 17  Profit             100000 non-null  float64
 18  Profit_Margin_Pct  100000 non-null  float64
 19  Month              100000 non-null  int64
 20  Month_Name         100000 non-null  str
 21  Quarter            100000 non-null  str
 22  Year               100000 non-null  int64
 23  Day_Name           100000 non-null  str
 24  Weekend            100000 non-null  str
dtypes: float64(9), int64(4), str(12)
memory usage: 19.1 MB

1. Bar Chart — Q1–Q5
Calculate the total Sales for each City and create a bar chart.
Calculate the total Profit for each Category and create a bar chart.
Calculate the average Customer Rating for each City.
Calculate the total Quantity sold for each Product.
Calculate the average Profit Margin (%) for each Customer Segment.
2. Horizontal Bar — Q6–Q10
Create a horizontal bar chart showing total Sales by City.
Show the top 10 Products by total Profit.
Show the top 10 Cities by total Quantity sold.
Show the average Sales by Customer Segment.
Show the total Profit by Payment Method, sorted from highest to lowest.
3. Grouped Bar — Q11–Q15
Compare total Sales across Cities for each Channel.
Compare total Profit across Categories for each Customer Segment.
Compare average Customer Rating across Cities for Store vs Marketplace.
Compare total Quantity sold across Categories for each Channel.
Compare average Discount (%) across Cities for each Customer Segment.
4. Stacked Bar — Q16–Q20
Show total Sales by City and Channel using a stacked bar chart.
Show total Profit by Category and Customer Segment.
Show order count by City and Payment Method.
Show total Quantity by Category and Channel.
Show order count by City and Weekend status.
5. Line Chart — Q21–Q25
Plot monthly total Sales.
Plot monthly total Profit.
Plot monthly total Quantity sold.
Plot monthly average Customer Rating.
Plot monthly average Discount (%).
6. Multiple Line — Q26–Q30
Plot monthly Sales for each City.
Plot monthly Profit for each Category.
Compare monthly Sales for Store and Marketplace.
Plot monthly Quantity sold for each Channel.
Compare monthly Sales and Profit on the same chart.
7. Pie Chart — Q31–Q35
Show the percentage distribution of orders by City.
Show the percentage distribution of Sales by Category.
Show the percentage distribution of orders by Channel.
Show the percentage distribution of orders by Customer Segment.
Show the percentage distribution of orders by Payment Method.
8. Donut Chart — Q36–Q40
Create a donut chart showing Sales contribution by City.
Show Profit contribution by Category.
Show order distribution by Channel.
Show order distribution by Customer Segment.
Show Sales contribution by Payment Method.
9. Scatter Plot — Q41–Q45
Plot Quantity vs Sales.
Plot Discount (%) vs Profit.
Plot Unit Price vs Sales.
Plot Customer Rating vs Sales.
Plot Customer Age vs Sales.
10. Bubble Chart — Q46–Q50
Plot Quantity vs Sales, with bubble size based on Profit.
Plot Discount (%) vs Profit, with bubble size based on Sales.
Plot Unit Price vs Sales, with bubble size based on Quantity.
Plot Customer Age vs Sales, with bubble size based on Customer Rating.
Plot Sales vs Profit, with bubble size based on Quantity.
11. Histogram — Q51–Q55
Plot the distribution of Sales.
Plot the distribution of Profit.
Plot the distribution of Quantity.
Plot the distribution of Customer Age.
Plot the distribution of Customer Rating.
12. Box Plot — Q56–Q60
Create a box plot of Sales by City.
Create a box plot of Profit by Category.
Create a box plot of Sales by Channel.
Create a box plot of Customer Rating by Customer Segment.
Create a box plot of Discount (%) by Category.
13. Violin Plot — Q61–Q65
Show the distribution of Sales across Cities.
Show the distribution of Profit across Categories.
Show the distribution of Sales across Channels.
Show the distribution of Customer Rating across Customer Segments.
Show the distribution of Discount (%) across Categories.
14. Area Chart — Q66–Q70
Plot monthly total Sales using an area chart.
Plot monthly total Profit.
Plot monthly total Quantity sold.
Plot monthly total Cost.
Plot monthly total Discount Amount.
15. Stacked Area — Q71–Q75
Show monthly Sales by City using a stacked area chart.
Show monthly Profit by Category.
Show monthly Sales by Channel.
Show monthly Quantity by Customer Segment.
Show monthly Sales by Payment Method.
16. Step Chart — Q76–Q80
Plot monthly Sales using a step chart.
Plot monthly Profit using a step chart.
Plot monthly Quantity sold.
Plot monthly average Customer Rating.
Plot monthly average Discount (%).
17. Stem Plot — Q81–Q85
Create a stem plot of monthly total Sales.
Create a stem plot of monthly total Profit.
Create a stem plot of monthly Quantity sold.
Create a stem plot of monthly average Customer Rating.
Create a stem plot of monthly average Discount (%).
18. Error Bar — Q86–Q90
Plot average Sales by City with standard deviation as error bars.
Plot average Profit by Category with standard deviation.
Plot average Customer Rating by City with standard deviation.
Plot average Sales by Channel with standard deviation.
Plot average Profit by Customer Segment with standard deviation.
19. Heatmap — Q91–Q95
Create a correlation heatmap of numerical columns.
Create a heatmap showing average Sales by City and Month.
Create a heatmap showing average Profit by Category and Month.
Create a heatmap showing average Sales by City and Channel.
Create a heatmap showing average Customer Rating by City and Customer Segment.
20. Hexbin Plot — Q96–Q100
Create a hexbin plot of Quantity vs Sales.
Create a hexbin plot of Discount (%) vs Profit.
Create a hexbin plot of Unit Price vs Sales.
Create a hexbin plot of Customer Age vs Sales.
Create a hexbin plot of Sales vs Profit.
21. Contour Plot — Q101–Q105
Create a contour plot showing the relationship between Discount (%) and Profit.
Create a contour plot for Quantity and Sales.
Create a contour plot for Unit Price and Sales.
Create a contour plot for Customer Age and Sales.
Create a contour plot for Sales and Profit.

⚠️ Contour plot raw categorical data ke liye nahi hota. Iske liye pehle suitable numeric grid/interpolation banana padega.

22. Polar Plot — Q106–Q110
Create a polar plot showing monthly Sales.
Create a polar plot showing monthly Profit.
Create a polar plot showing monthly Quantity sold.
Create a polar plot showing monthly average Customer Rating.
Create a polar plot showing monthly average Discount (%).
23. ECDF Plot — Q111–Q115
Create an ECDF plot for Sales.
Create an ECDF plot for Profit.
Create an ECDF plot for Quantity.
Create an ECDF plot for Customer Age.
Create an ECDF plot for Customer Rating.
24. 2D Histogram — Q116–Q120
Create a 2D histogram of Quantity vs Sales.
Create a 2D histogram of Discount (%) vs Profit.
Create a 2D histogram of Unit Price vs Sales.
Create a 2D histogram of Customer Age vs Sales.
Create a 2D histogram of Sales vs Profit.
25. Stackplot — Q121–Q125
Create a stackplot showing monthly Sales by City.
Create a stackplot showing monthly Profit by Category.
Create a stackplot showing monthly Sales by Channel.
Create a stackplot showing monthly Quantity by Customer Segment.
Create a stackplot showing monthly Sales by Payment Method.